spring.application.name=demo
app.message=Hello from properties (changed).

my.props.age=19
my.props.name=krishnapravin


##for datasource
##spring.datasource.jndi-name=java:comp/env/jdbc/myDataSource
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url= jdbc:oracle:thin:@//localhost:1521/orcl
#spring.datasource.username=c##krishna
#spring.datasource.password= krishna


# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?sslmode=disable
#spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true